# Form implementation generated from reading ui file 'AboutTheProgram.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutTheProgram(object):
    def setupUi(self, AboutTheProgram):
        AboutTheProgram.setObjectName("AboutTheProgram")
        AboutTheProgram.resize(395, 301)

        self.retranslateUi(AboutTheProgram)
        QtCore.QMetaObject.connectSlotsByName(AboutTheProgram)

    def retranslateUi(self, AboutTheProgram):
        _translate = QtCore.QCoreApplication.translate
        AboutTheProgram.setWindowTitle(_translate("AboutTheProgram", "Form"))
